services:
  - type: web
    name: pdf-summarizer
    env: docker
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 